### ISSUE TITLE
Firebase 9.4.0 and MacOS arm64

### ISSUE THREAD

**Issue by snorrsi** [GameWorkstore/com.google.firebase.app#12]
Firebase for Unity 9.4.0 is out.
Will update the packages this week.
I need to look into the MacOS Silicon lipo fix.
Thought initially it was working but it seems not to be fully working as firebase seems to be looking for the corresponding bundle file with name.
Might need to build the package by myself to fix that issue.

**Comment by snorrsi** [comment]
It seems Unity is sometimes complaining about bundle with same name even though the settings are such that only arm64 or x86_64 should be loaded. Not sure if it was only due to git getting older tag by cache.

9.4.0 tag should now hopefully work. Please let use know here it works for you or not

**Comment by andnoonesthere** [comment]
For us it worked fine.

**Comment by snorrsi** [comment]
@andnoonesthere great.. I just add 9.5.0
