### ISSUE TITLE
Version 11.0

### ISSUE THREAD

**Issue by Girildo** [GameWorkstore/com.google.firebase.app#14]
Hi guys,
Version 11.0 of the Firebase SDK has been released on May 9th.
Are you planning on updating this very valuable repository?

Thanks for the great service!

**Comment by andnoonesthere** [comment]
Maybe it's worth to update to 11.1 as it seems to contain important fix for some ANRs we're struggling with? @snorrsi

**Comment by snorrsi** [comment]
Hi @Girildo and @andnoonesthere ,

I haven’t been using Unity for work for some time and asked @HanzaRu to take over updating the repositories

**Comment by snorrsi** [comment]
Hi @Girildo , @andnoonesthere , @HanzaRu 

I just created 11.1.0 tags, let me know here if you have any issues.
(We will just skip 11.0.0 since it seems somewhat broken)

**Comment by HanzaRu** [comment]
Hi, as I'm overloaded with work I'm accepting new managers to update the repos @Girildo and @andnoonesthere , let me know if you are interested on this issue: https://github.com/GameWorkstore/com.google.firebase.app/issues/16

**Comment by Girildo** [comment]
If it is about updating a tag when a new version is released I think I can do it.
