### ISSUE TITLE
Calling for Google/Firebase Repos update volunteers

### ISSUE THREAD

**Issue by HanzaRu** [GameWorkstore/com.google.firebase.app#16]
Hi guys, as I'm overloaded by the other GameWorkstore packages and my everyday job (protocolui, patterns, protocolaudio, fsm, asyncnetworkengine and new packages), I'm opening positions for volunteers to update google & firebase packages. Please candidate yourselves on this thread, I will enter in contact as soon I check your credentials to manage our repos,

The process of update the firebase packages takes just few minutes, but it needs constant vigilance on the google pages,

Cheers
John

**Comment by andnoonesthere** [comment]
Hello @HanzaRu I would be happy to help with this.

**Comment by xmeng1** [comment]
we are using a private npm register to serve it. Jetbrain space has free usage which is enough for there firebase packages.

**Comment by StinkySteak** [comment]
Is there no update on this? I do similar as you, hosting the package as UPM. currently stuck with 11.2.0, I think I have to upgrade to the latest version because there is a comply issue with the com.google.android.gms.play-services-measurement-impl-21.3.0.aar

**Comment by HanzaRu** [comment]
@andnoonesthere and anyone who wants to contribute on firebase updates, send me a email on contact@gameworstore.com so we can schedule a call
