### ISSUE TITLE
Firebase 8.4.0 is out

### ISSUE THREAD

**Issue by snorrsi** [GameWorkstore/com.google.firebase.app#3]
dear owner,

It would be greatly appreciated if you could update your repo to include Firebase 8.4.0 for Unity as it was recently released.

best regards,
Snorri

**Comment by john-rosa-playkids** [comment]
Hi @snorrsi, I will be updating it on the weekend!

I also would like to invite you to join the @GameWorkstore open-source organization for contributing with google package management, if you wish. Let me know your thoughts,

Kind Regards,
Hanza

**Comment by snorrsi** [comment]
Hi @john-rosa-playkids,

sure, could do that.. just send me what you have in mind to my gmail (snorrsi)

best regards,
Snorri
