### ISSUE TITLE
8.7.0 Update

### ISSUE THREAD

**Issue by andnoonesthere** [GameWorkstore/com.google.firebase.app#5]
It seems to contain some important iOS fixes. Can you please update it? :)

**Comment by john-rosa-playkids** [comment]
Hi @andnoonesthere ,

I will be updating on Saturday, 
Thank you for letting me know about the update :D

Kind Regards,
Hanza

**Comment by john-rosa-playkids** [comment]
I found some time to update this afternoon! All repos are updated to date.

Let me know if you find any missing updates, otherwise we can close this issue,
Cheers,
Hanza

**Comment by snorrsi** [comment]
Awesome.. thanks.. will test it in few minutes

**Comment by snorrsi** [comment]
@john-rosa-playkids looks fine for me.. all packages I use got included at least.

**Comment by john-rosa-playkids** [comment]
Closing it!
