### ISSUE TITLE
Firebase Unity SDK 8.9.0 needed

### ISSUE THREAD

**Issue by snorrsi** [GameWorkstore/com.google.firebase.app#7]
dear owner,

It would be greatly appreciated if you could update your repo to include Firebase 8.9.0 for Unity as it was recently released and includes some fixes for iOS 15.

best regards,
Snorri

**Comment by andnoonesthere** [comment]
@HanzaRu same for me, I would be very grateful for updating it :)

**Comment by snorrsi** [comment]
Hey @HanzaRu , think you can update the Firebase packages soon-ish ? :)

**Comment by HanzaRu** [comment]
Ha, hello everyone, for some reason I didn't received a notification of this new issue, try to assign me to ensure faster response, i will be updating through this weekend, I let you know when it's done!

**Comment by HanzaRu** [comment]
Done, let me know if find something out of place, otherwise, I will close the thread anytime soon.

**Comment by snorrsi** [comment]
@HanzaRu thanks a lot .. looks fine to me :)
