### ISSUE TITLE
Schedule a Video call for updating training

### ISSUE THREAD

**Issue by HanzaRu** [GameWorkstore/com.google.firebase.app#8]
Hello @snorrsi , when a new version appears, send me an email on the image to schedule a training call on how to upgrade the google package versions!

![image](https://user-images.githubusercontent.com/16651384/166706583-6aa082ef-2772-4e47-96fa-b3c89164b33a.png)

You can close this issue when you see this message,
See you around,
Hanza

**Comment by snorrsi** [comment]
@HanzaRu sent you email few days ago
